development:
  adapter: postgresql
  database: ci_web_development
  #user: postgres
  pool: 50
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: ci_web_development
  #user: postgres
  pool: 50
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: ci_web_test
  #user: postgres
  pool: 50
  timeout: 5000
  host: localhost
