development:
  adapter: postgresql
  database: ci_web_development
  user: postgres
  pool: 20
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: ci_web_test
  user: postgres
  pool: 20
  timeout: 5000
  host: localhost
