default: &default
  adapter: postgresql
  pool: 50
  timeout: 5000
  user: postgres
  host: localhost

development:
  <<: *default
  database: ci_web_development

production:
  <<: *default
  database: ci_web_development

test:
  <<: *default
  database: ci_web_test
